Updates and fixes to ldap-dump and ldap-load scripts

diff --git a/usr/bin/ldap-dump-db b/usr/bin/ldap-dump-db
--- a/usr/bin/ldap-dump-db
+++ b/usr/bin/ldap-dump-db
@@ -4,7 +4,7 @@
 
 if [ "$1" = "help" ]
 then
-    echo "Usage: ldap-dump-db [help|manual]"
+    echo "Usage: ldap-dump-db [help|manual|force]"
     exit 1
 fi
 if [ "$1" = "manual" ]
@@ -17,26 +17,32 @@ then
     forceSW="-f"
 fi
 
-source /etc/ldap-dump.conf
-
 thisDate=`date +%Y%m%d`
 thisYear=`date +%Y`
 thisMonth=`date +%m`
 outDir="/afs/.cz/backup/ldap/${thisYear}/${thisMonth}"
 thisHost=`hostname`
 
-for baseDN in $BASEDN_LIST
-do
-    rdn="${baseDN%%,*}"
-    dbid="${rdn#dc=}"
-    fullDB="${dbid}.ldif"
+# Read a configuration file if there is one
+source /etc/ldap-backup.conf
+if [ "$DBID" = "" ]
+then
+    echo "ERROR: DBID missing"
+    exit 1
+fi
 
-    echo "starting dump to /tmp/$fullDB ..."
-    /usr/sbin/slapcat -o ldif-wrap=no -b $baseDN > /tmp/$fullDB
+fullDB="${thisHost%%.*}-${DBID}-${thisDate}.ldif"
+dbRoot="db-${DBID}.ldif"
 
-    echo "compressing $fullDB ..."
-    /bin/gzip $forceSW /tmp/$fullDB
-done
+echo "starting dump to /tmp/$fullDB ..."
+/usr/sbin/slapcat -o ldif-wrap=no -b $DBDN > /tmp/$fullDB
+
+echo "compressing $fullDB ..."
+/bin/gzip $forceSW /tmp/$fullDB
+cp -v /tmp/${fullDB}.gz /tmp/${dbRoot}.gz
+
+echo "Copying ${fullDB}.gz to $outDir ..."
+cp -v $forceSW /tmp/${fullDB}.gz $outDir
 
 ##############################################################################
 # Documentation
@@ -44,7 +50,7 @@ done
 DOCS=<<__END_OF_DOCS__
 =head1 NAME
 
-ldap-dump-db - Dump LDAP databases
+ldap-dump-db - Dump the LDAP database
 
 =head1 SYNOPSIS
 
@@ -52,20 +58,24 @@ ldap-dump-db [help|manual|force]
 
 =head1 DESCRIPTION
 
-<<<<<<< HEAD
-This script dumps LDAP data defined in the /etc/ldap-dump.conf shell
-fragment.  The files are dumped to file in /tmp and compressed.
-=======
-This script dumps the dc=macallister,dc=grass-valley,dc=ca,dc=us and
-the dc=ca-zephyr,dc=org databases in LDIF format to the file 
-/tmp/db-ldif.0.gz. A date stamped copy of the file is also saved in the
+This script dumps the LDAP data base in LDIF format and compresses it.
+A date stamped copy of the file is also saved in the
 /afs/cz/backup/ldap/<year>/<month> AFS directory.
->>>>>>> ldap-dump changes
 
 The local slapd server is NOT stopped during the dump.
 
 The force action overwrites output files without prompting for 
 confirmation.
+
+=head1 CONFIGURATION
+
+The script will source the file /etc/cz-ldap.conf if it exists.  This 
+can be used to override values for the following variables:
+
+    thisDate=`date +%Y%m%d`
+    thisYear=`date +%Y`
+    outDir="/afs/.cz/backup/ldap/${thisYear}"
+    thisHost=`hostname`
 
 =head1 OPTIONS
 
@@ -81,13 +91,9 @@ This documentation.
 
 =back
 
-=head1 SEE ALSO
-
-ldap-dump-wrapper
-
 =head1 AUTHOR
 
-Bill MacAllister <whm@cz-zephyr.org>
+Bill MacAllister <bill@ca-zephyr.org>
 
 =cut
 __END_OF_DOCS__
diff --git a/usr/bin/ldap-load-db b/usr/bin/ldap-load-db
--- a/usr/bin/ldap-load-db
+++ b/usr/bin/ldap-load-db
@@ -31,7 +31,7 @@ function del {
 # Set the configuration to use for the load
 if [ "$1" = "help" ]
 then
-    echo "Usage: ldap-load-db [db] [help|manual|files|config]"
+    echo "Usage: ldap-load-db [help|manual|files|config]"
     exit 1
 fi
 if [ "$1" = "manual" ]
@@ -41,16 +41,14 @@ then
 fi
 
 # Get the database to reload
-if [ "$1" = "" ]
+source /etc/ldap-backup.conf
+if [ "$DBID" = "" ]
 then
-    echo "ERROR: db required as parameter 1"
-    echo ""
-    echo "Valid dbs are:"
-    ls -d /var/lib/ldap/*
+    echo "ERROR: DBID missing"
     exit 1
 fi
-db=$1
-dbDir="/var/lib/ldap/$db"
+
+dbDir="/var/lib/ldap/$DBID"
 if [ -e $dbDir ]
 then
     echo "Cleaning out $dbDir"
@@ -76,41 +74,17 @@ else
     echo "Using $config for load"
 fi
 
-if [ "$db" = "macallister" ]
-then
-    dbDN="dc=macallister,dc=grass-valley,dc=ca,dc=us"
-else
-    if [ "$db" = "ca-zephyr" ]
-    then
-        dbDN="dc=ca-zephyr,dc=org"
-    else
-        echo "Unknown dbid."
-        exit 1
-    fi
-fi
-
 cd /tmp
 
-dbRoot="/tmp/db-ldif-${db}.0"
+dbRoot="/tmp/db-${DBID}.ldif"
 dbFile="${dbRoot}.gz"
-dbBackup="/tmp/db-ldif-backup-${db}.0.gz"
 if [ ! -e $dbFile ]
-    then
-    if [ -e $dbBackup ]
-        then
-        echo "Restoring $dbBackup ..."
-        cp $dbBackup $dbFile
-    else
-        echo "ERROR: no input files found."
-        echo "Files: $dbBackup or ${dbFile}."
-        echo "FATAL ABORT"
-        exit 1
-    fi
+then
+   echo "ERROR: input file not found. ($dbFile)"
+   exit 1
 fi
 
 del $dbRoot
-del $dbBackup
-cp $dbFile $dbBackup
 
 echo "Uncompressing ..."
 /bin/gunzip $dbFile
@@ -124,7 +98,7 @@ touch /etc/noldap
 /usr/sbin/service slapd stop
 
 # Clean out the current database
-del /var/lib/ldap/$db/*
+del /var/lib/ldap/$DBID/*
 if [ -e /var/lib/ldap/accesslog ]
 then
     del /var/lib/ldap/accesslog/*
@@ -138,7 +112,7 @@ sync
 set +o noclobber
 echo 3 > /proc/sys/vm/drop_caches
 
-/usr/sbin/slapadd -q $config -b $dbDN -l $dbRoot
+/usr/sbin/slapadd -q $config -b $DBDN -l $dbRoot
 
 echo "Load complete.  Don't forget to start slapd."
 
@@ -158,7 +132,7 @@ ldap-load-db dbID [help|manual|files|config]
 This script uses slapadd to load an OpenLDAP directory.  The database
 directory is assumed to be in /var/lib/ldap.  The accesslog directory
 will be created if needed.  The input LDIF file is assumed to be
-/tmp/db-ldif-<dbID>.0.gz.
+/tmp/db-<dbID>.gz.
 
 The load process is very careful about the input LDIF file.  It is
 backed up before being uncompressed and will be restored if the
